### ISSUE TITLE
Upload media with command

### ISSUE THREAD

**Issue by pdenis** [open-orchestra/open-orchestra-media-bundle#133]
Hi,

When we try to create a media with a command, media upload is not handled. 
We have the same problem for thumbnail generation. 

Uploads are manage with Kernel Terminate event but we haven't this event in console mode. 
It would be usefull to plug also Console Terminate event to allow command media upload. 

thx

**Comment by nicolasThal** [comment]
Hi,

As we do not handle command media upload, I suggest that you override the subscriber in your project to add the ConsoleEvents::TERMINATE in the subscribed events.

Regards.
