### ISSUE TITLE
Add a twig function to generate format Url without displaying preview

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-media-bundle#164]
The twig method get_media_format_url depend on the media strategy you use to implement media. In my context the media type has no importance, I just want the media Url to let the front user download the media.

**Comment by itkg-ngilain** [comment]
@itkg-mraiffe: The media twig helpers have been rewrote. I think you can have what you want with https://github.com/open-orchestra/open-orchestra-media-bundle/blob/master/Media/Twig/DisplayMediaExtension.php#L43
Is it ok for you ?

**Comment by itkg-mraiffe** [comment]
:+1:
