### ISSUE TITLE
After crop image which display don't correspond

### ISSUE THREAD

**Issue by glenouvel** [open-orchestra/open-orchestra-media-bundle#174]
Version 1.1.0-ALPHA 4

When I want crop a media, i select my area with my pointer. When i submit with Crop button , form is refresh but the picture which is displayed is the same i have crop. 

I have reproduced this issue on open-orchestra demo site

**Comment by alavieille** [comment]
it's fix, you can test when the next version is tagged ?

**Comment by alavieille** [comment]
@glenouvel You still have the bug ?

**Comment by glenouvel** [comment]
@alavieille : We have not made the migration yet, but I have made some tests in oo integration and it's ok
