### ISSUE TITLE
1.1.1 After crop image which display don't correspond (#174)

### ISSUE THREAD

**Issue by itkg-mraiffe** [open-orchestra/open-orchestra-media-bundle#200]
Version 1.1.1

When I want crop a media,I select my area with my pointer. When I submit with Crop button , form is refresh but the picture which is displayed is not the image I selected or the crop did not display anaything

In the Open-Orchestra inte Website the problem is different but the crop is not working too.

**Comment by itkg-nanne** [comment]
fixed for 1.2 (https://github.com/open-orchestra/open-orchestra-media-admin-bundle/pull/244)
