### ISSUE TITLE
MediaInterface should use Collection instead of ArrayCollection

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-media-bundle#217]
## Informations
**Orchestra Version** : 
1.0, 1.1, master

**Issue Type**: 
- [ ] Bug
- [x] Feature request
- [ ] Question

## Description

The [MediaInterface](https://github.com/open-orchestra/open-orchestra-media-bundle/blob/master/Media/Model/MediaInterface.php) have some methods which have `ArrayCollection` as return type. This should be a `Doctrine\Common\Collections\Collection` to avoid conflicts with other collections.

**Comment by alavieille** [comment]
This is fixed with this PR https://github.com/open-orchestra/open-orchestra-media-bundle/pull/219. thanks
