### ISSUE TITLE
Give ability to pass html attributes in display_media twig function

### ISSUE THREAD

**Issue by itkg-canne** [open-orchestra/open-orchestra-media-bundle#220]
## Informations
**Orchestra Version** : 1.2

**Issue Type**: 
- [ ] Bug
- [x] Feature request
- [ ] Question

## Description
To limit HTML tags encapsulation, it could be useful to give ability to pass HTML attributes to the media view through the `display_media` twig function.

For example `display_media(mediaId, 'original', array('id' => 'my-media', 'class' => 'fullsize'))`.

**Comment by ngilain** [comment]
We will do this in 1.2

**Comment by alavieille** [comment]
There is added in this PR https://github.com/open-orchestra/open-orchestra-media-bundle/pull/224
