### ISSUE TITLE
Slideshow question with IE11

### ISSUE THREAD

**Issue by mmbourgc** [open-orchestra/open-orchestra-media-bundle#225]
## Informations

**Orchestra Version** :  1.1.2

**Issue Type**: 

- [ ] Bug
- [ ] Feature request
- [x] Question

## Description

I tried to use the slideshow block. It works fine with chrome and firefox but doesn't display anything on ie(11) because of a javascript error in blockLoader.js on line 12 openOrchestraCss.load(['/bundles/openorchestramedia/block/Slideshow/css/style.css']).

The openOrchestraCss object is not initialized.

Can you confirm the issue or is it specific to my server ?

**Comment by alavieille** [comment]
Yes i confirm this issue. we will see it.

**Comment by alavieille** [comment]
This is fixed in this PR https://github.com/open-orchestra/open-orchestra-display-bundle/pull/240
Thanks
