### ISSUE TITLE
[Insight] Unused use statement should be avoided - in …/OpenOrchestraMediaExtension.php, line 13

### ISSUE THREAD

**Issue by nicolasThal** [open-orchestra/open-orchestra-media-bundle#64]
**[in MediaBundle/DependencyInjection/OpenOrchestraMediaExtension.php, line 13](https://github.com/open-orchestra/open-orchestra-media-bundle/blob/c3d6f73e731fa2aaefc6cb76f073570acd0e2625/MediaBundle/DependencyInjection/OpenOrchestraMediaExtension.php#L13)**

> The class `Symfony\Component\DependencyInjection\Definition` is declared but never used. You should remove the `use` statement.

```php
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\HttpKernel\DependencyInjection\Extension;
use Symfony\Component\DependencyInjection\Loader;
use Symfony\Component\DependencyInjection\Reference;
use Symfony\Component\DependencyInjection\Definition;

/**
 * This is the class that loads and manages your bundle configuration
 *
 * To learn more see {@link http://symfony.com/doc/current/cookbook/bundles/extension.html}
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/eb401ccd-7602-460a-a947-92416e54ea52/analyses/52)_

**Comment by itkg-alavieille** [comment]
already resolved
