### ISSUE TITLE
Improve ImageResizerManager to allow dynamic formats for crop method and no resize

### ISSUE THREAD

**Issue by clement-michelet** [open-orchestra/open-orchestra-media-bundle#71]
If you want to apply crop transformation image without resize transformation, you can't as the format is mandatory. You also cannot modify the pre-defined format on the fly as a workaround.

Proposal:
* crop action must only be used for cropping image (i.e. remove resize part)
* introduce a new method cropAndResize for doing both crop and resize action
* allow to add new formats

**Comment by nicolasThal** [comment]
You can add new formats with the `open_orchestra_media.thumbnail` configuration key.

When you do a crop action, we have to garantie that the result will still be in the constraint you give (heigh, width or both) that's the reason fo the resize
