### ISSUE TITLE
Uploaded files stuck in /tmp

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra-media-bundle#90]
When a file is uploaded it is moved to the media tmp directory (/tmp by default), but it's never cleaned up. As /tmp is flushed during reboot and servers are likely to almost never be rebooted, this is an issue.

**Comment by itkg-alavieille** [comment]
it is fix in this PR : 
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/98/files
and 
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/103/files
