### ISSUE TITLE
Media persist listener can't handle multiple file upload

### ISSUE THREAD

**Issue by juchi** [open-orchestra/open-orchestra-media-bundle#91]
The listener has an attribute "$filename" that holds the processed filename after the prepersist call. If I upload several files at once, I cannot persist them all and flush just once, as the filename will be the one of the last file persisted. I have to flush after the persist of each media object, which is not ideal.

**Comment by nicolasThal** [comment]
https://github.com/open-orchestra/open-orchestra-media-bundle/pull/105
